spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8
    username: ENC(A6bs9PFdqSREKHU6ZT2X/A==)
    password: ENC(FaWhFpcpyykwCtIcbPTDqw==)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG


jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # Swagger UI ??
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
  paths-to-match: /**
  packages-to-scan: com.portfolio.kim
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


---



spring:
  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8
    username: ENC(${JASYPT_ID})
    password: ENC(${JASYPT_PASSWORD})
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX



jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    pool-size: 4


server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /





---


spring:
  config:
    activate:
      on-profile: operation
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8
    username: ENC(A6bs9PFdqSREKHU6ZT2X/A==)
    password: ENC(FaWhFpcpyykwCtIcbPTDqw==)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 80
  shutdown: graceful
  servlet:
    context-path: /
